const menu = [
    {
        id: "jhnlkjhn",
        name: "Ellora and Ajanta caves",
        info: "Ajanta and Ellora are two monumental rock-cut caves that define Indian art and architectural accomplishment. Though these two monuments are separated by a distance of approximately 100 km, they are often mentioned together since their aesthetics and importance are at par and the fact that both are situated in the Aurangabad district of Maharashtra. While Ajanta is mostly about beautiful paintings made on cave walls on the theme of Buddhism, Ellora is all about sculpture and architecture belonging to three different religions prevailing in the country during those times—Buddhism, Hinduism and Jainism.",
        image: "https://www.onacheaptrip.com/wp-content/uploads/Kailasa-Temple-at-Ellora-Caves-Aurangabad.jpg",
        country: "India",
        category: "antiquities",
    },
    {
        id: "jhfgjfg",
        name: "The Monkey Island in Nha Trang",
        info: "In the past, the island looked like a casuarina (“Phi Lao” in Vietnamese), therefore it was called by the locals ” Hon Lao” (means the island of casuarinas). After that, in 1975, the monkeys were brought here by the So Viet Union specialists and raised for scientific purposes. They then spawned on their own, and now there are more than 1,200 monkeys living in herds on the island. That is the reason why this island is also called Monkey Island, besides its official name “Hon Lao”.",
        image: "https://ak.jogurucdn.com/media/image/p14/place-2014-09-23-18-Monkeyisland6a6887b9a2a1e4fbb487a22b507a43ac.jpg",
        country: "Vietnam",
        category: "nature",
    },
    {
        id: "fdghdfh",
        name: "Kiraly baths in Budapest",
        info: "In the past, the island looked like a casuarina (“Phi Lao” in Vietnamese), therefore it was called by the locals ” Hon Lao” (means the island of casuarinas). After that, in 1975, the monkeys were brought here by the So Viet Union specialists and raised for scientific purposes. They then spawned on their own, and now there are more than 1,200 monkeys living in herds on the island. That is the reason why this island is also called Monkey Island, besides its official name “Hon Lao”.",
        image: "https://34travel.me/media/upload/images/2015/november/Budapest%20termal/Sunshine-in-Kiraly-Bath-Turkish-Baths-Budapest(1).jpg",
        country: "Hungary",
        category: "baths",
    },
    {
        id: "jghfjhj",
        name: "QC Terme Bagni Vecchi",
        info: "The spa's name, which means the old baths, is a reference to the fact that this is the oldest spa in the region. There have been baths here for more than 2,000 years, which is part of its unique appeal. In addition to the Roman baths, which are in all probability the original baths of the Ancient Romans, the Bagni Vecchi also includes Mediaeval Baths, the Imperial Baths and the Baths of the Archduchess. Not forgetting the remarkable San Martino spring which is the only example in the whole of the Alps of a \"sweating grotto\", a natural and therapeutic sauna. And then there is the infinity pool overlooking Bormio.",
        image: "https://d3qvqlc701gzhm.cloudfront.net/full/1dad349c13a51aa531cb2d0e98a48a007a938e7bdb6524b3910bfaa792aab881.jpg",
        country: "Italy",
        category: "baths",
    },
    {
        id: "jfgjhfh",
        name: "Palaces in Luxor",
        info: "Luxor is a modern city in Upper (southern) Egypt which includes the site of the Ancient Egyptian city of Thebes. Luxor has frequently been characterized as the \"world's greatest open-air museum\", as the ruins of the Egyptian temple complexes at Karnak and Luxor stand within the modern city. Immediately opposite, across the River Nile, lie the monuments, temples and tombs of the west bank Theban Necropolis, which includes the Valley of the Kings and Valley of the Queens. Thousands of tourists from all around the world arrive annually to visit Luxor's monuments, contributing greatly to the economy of the modern city. The population of Luxor is 422, 407 (2021), with an area of approximately 417 km2 (161 sq mi).[2] It is the capital of Luxor Governorate. It is among the oldest inhabited cities in the world.",
        image: "https://d3rr2gvhjw0wwy.cloudfront.net/uploads/mandators/49581/file-manager/luxor_temple.jpg",
        country: "Egypt",
        category: "antiquities",
    },
    {
        id: "tyutut",
        name: "Vagator beach",
        info: "At Vagator Beach, a curved stretch of sand overlooked by the Chapora Fort, you will find a lot of activities occurring simultaneously. Decent sized bars serve food & drinks, a cricket game in progress & vendors selling refreshing coconut water. The beach is dotted with a hillock on one side & headland on the other. Located in north Goa, it is situated at the end of the Sinquerim, Candolim, Calangute, Baga & Anjuna stretch, and is separated from Morjim by the Chapora River. The beach itself is divided into two parts, Big Vagator & Little Vagator. You should try & visit this beach during your holidays in Goa, not just because it promises you a lovely time, but also because it is “the most photographed beach in Goa”. Besides watching the sunset, you can also try out a variety of water sports.",
        image: "https://www.visittnt.com/images/goa/Vagator-Beach.jpg",
        country: "India, Goa",
        category: "beach",
    },
    {
        id: "ujtutyu",
        name: "Anjuna flea market",
        info: "Anjuna Flea market is a hippie's paradise in Goa where you can find a treasure trove of souvenirs, handicrafts, hippie clothes, and trinkets at a drift cheap rate. This weekly market started in the 1960s as a way for the hippie travelers to barter their unique products. In the beginning, it was called the open-air goods exchange market by the locals, but now it has become a popular attraction for tourists and locals alike. Earlier, this flea market was organized on a small area of the beach, but now it extends from the golden shores of the beach to the paddy fields with plenty of stalls selling tidbits.",
        image: "https://i0.wp.com/goaprism.com/wp-content/uploads/2014/07/anjuna-flea-market.jpg",
        country: "India, Goa",
        category: "relax",
    },
];

export default menu;